In [2]:
import numpy as np

In [233]:
# [Array stacking] Assume that the two stacking methods vstack() and hstack() were
# not available. Write a Python program using NumPy that allows to concatenate two
# two-dimensional arrays, each with at least 2 rows and 2 columns, either horizontally or
# vertically. Your solution should solely be based on NumPy array creation facilities and slicing
# operations.
# Hint: use an intermediate (buffer) array for performing the concatenation!

In [3]:
numbers = np.array([[10, 20, 30],
                    [40, 50, 60]])
grades=np.array([[1, 2, 3],
                    [4, 5, 6]])

In [4]:
def my_hstack(numbers, grades):
    mid = np.array([i for i in zip(numbers, grades)])
    mid.resize(grades.shape[0], grades.shape[1]*2)
    return mid

In [5]:
def my_vstack(numbers, grades):
    return np.concatenate((numbers, grades))

In [6]:
my_hstack(numbers, grades)

array([[10, 20, 30,  1,  2,  3],
       [40, 50, 60,  4,  5,  6]])

In [7]:
my_vstack(numbers, grades)

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [243]:
# 2. [Array statistics] Write a Python program that takes a NumPy integer array of arbitrary shape
# and determines the most frequent value (=mode) in the whole array! This should be
# accomplished without the use of any extra libraries (except for numpy). Test your program
# with a two-dimensional array that contains at least one value twice.

In [244]:
numbers = np.array([[10, 20, 30, 30, 5],
                    [40, 50, 60,40, 40]]).flatten()

In [245]:
def mode(numbers):
    valcounts= np.unique(numbers.flatten(), return_counts=True)
    values=valcounts[0]
    counts=valcounts[1]
    index = np.argmax(counts)
    return values[index]

In [246]:
mode(numbers)

40

In [247]:
# 3. [Bonus task: matrix multiplication] Give an implementation of “true” matrix multiplication in
# Python, based on NumPy arrays and loops only. A description of matrix multiplication can be
# found, for example, at
# https://www.mathsisfun.com/algebra/matrix-multiplying.html
# or, if you like it more formal:
# https://mathworld.wolfram.com/MatrixMultiplication.html
# Verify your result using function numpy.matmul()!
# Hint: use the shape attribute of the NumPy ndarray to create the required index
# ranges!
# Some helpful links to the numpy documentation:
# https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

In [248]:
num1=np.array([[1, 2, 3],
                    [4, 5, 6]])
num2=np.array([[1, 4], [2,5],
                    [3, 6]])

In [249]:
def matrixmult(x, y):
    return np.array([sum(i*j) for i in x for j in y.T]).reshape(x.shape[0], y.shape[1])

print(matrixmult(num1, num2))

[[14 32]
 [32 77]]


In [250]:
np.matmul(num1, num2)

array([[14, 32],
       [32, 77]])